# Generated by Django 5.1.3 on 2024-12-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar', '0002_remove_paciente_historico_medico_paciente_user'),
    ]

    operations = [
    ]
