# Generated by Django 5.1.3 on 2024-12-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar', '0004_alter_agendamento_status_alter_clinica_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='historico_medico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
